import type { Metadata } from "next";
import { Geist, Noto_Serif_Georgian, Geist_Mono } from "next/font/google";
import "./globals.css";
import db from "@/lib/supabase/db";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import AppStateProvider from "@/lib/providers/state-provider";
import { SupabaseUserProvider } from "@/lib/providers/supabase-user-provider";
//added this while making login page
import { DM_Sans } from "next/font/google";
import { twMerge } from "tailwind-merge";
import { Toaster } from "@/components/ui/sonner";

const inter = DM_Sans({ subsets: ["latin"] });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

//self change from Georgia (no longer available)
const fontSerif = Noto_Serif_Georgian({
	subsets: ["latin"],
	variable: "--font-serif",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	console.log(db);
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				//changed font to DM_Sans
				className={twMerge("bg-background", inter.className)}
				//  className={`${geistSans.variable} ${fontSerif.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<AppStateProvider>
						<SupabaseUserProvider>
							{children}
							<Toaster position="top-center" offset={0} />
						</SupabaseUserProvider>
					</AppStateProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}

